#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --disable-external --check-favicon --check-html --report-invalid-tags --report-missing-names --report-eof-tags --report-missing-doctype --report-mismatched-tags
